name: CD - Production

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-production:
    name: Deploy Production
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Deploy to Production
        run: pnpm exec vercel deploy --yes --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_PROJECT_ID: ${{ secrets.vcp_5yFvX2NJSYhG3G6s8jkYZi7s2lHlqScrwJeOotv7mBFMPm488n0VVV }} }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
